apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-signed-images
spec:
  validationFailureAction: enforce
  background: true
  rules:
    - name: check-signed-images
      match:
        resources:
          kinds:
            - Pod
      verifyImages:
        - image: "*"
          key: |
            -----BEGIN PUBLIC KEY-----
            # This will be replaced with the actual public key from Cosign
            -----END PUBLIC KEY-----
      mutateImages:
        - image: "*"
          key: |
            -----BEGIN PUBLIC KEY-----
            # This will be replaced with the actual public key from Cosign
            -----END PUBLIC KEY-----
