name: Destroy AWS Infrastructure

on:
  workflow_dispatch:  # This lets you trigger manually from the GitHub Actions UI

permissions:
  id-token: write
  contents: read


jobs:
  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActions
          aws-region: us-east-1  # or your configured region

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init -reconfigure

      - name: Terraform Show State
        working-directory: ./terraform
        run: terraform show

      - name: Terraform State List
        working-directory: ./terraform
        run: terraform state list

      - name: Terraform Destroy
        working-directory: ./terraform
        run: terraform destroy -auto-approve -input=false -var="aws_region=us-east-1"
